function hLib = HexagonCodeReplacementLibraryTable

thisFile = mfilename('fullpath');
[thisPath, ~] = fileparts(thisFile);
SplitPath = strsplit(thisPath,'\\');
SharedPath = fullfile(char(join(SplitPath(1:end-1),'\\')), 'shared');

hLib = RTW.TflTable;

%---------- entry: rfft_init ----------- 
hEnt = createCRLEntry(hLib, ...
    '[csingle y1[1 1; 1024 1024], csingle y2[1 1; 1024 1024]] = rfft_init( int32 u1 )', ...
    'void unused = rfft_init( csingle* y1, csingle* y2, const int32 u1 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'rfft_hexagon.h', ...
          'ImplementationSourceFile', 'rfft_hexagon.c', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'ImplementationSourcePath', fullfile(thisPath, 'src'), ...
          'GenCallback', 'RTW.copyFileToBuildDir', ...
          'AdditionalHeaderFiles', { ...
                'qhmath.h', ...
                'qhcomplex.h', ...
                'qhdsp.h', ...
                'qhdsp_common.h', ...
                'blkutil.h', ...
                'qhdsp_fft_internal.h'}, ...
          'AdditionalIncludePaths', { ...
                fullfile(thisPath, 'inc')}, ...
          'AdditionalSourceFiles', { ...
                'blkutil.c', ...
                'qhdsp_fft_internal.c'}, ...
          'AdditionalSourcePaths', { ...
                fullfile(thisPath, 'src')}, ...
          'SideEffects', true);



hLib.addEntry( hEnt ); 

%---------- entry: rfft_process ----------- 
hEnt = createCRLEntry(hLib, ...
    'csingle y1[1 1; 1024 1024] = rfft_process( single u1[1 1; 1024 1024], csingle u2[1 1; 1024 1024], csingle u3[1 1; 1024 1024], csingle u4[1 1; 1024 1024], int32 u5, int32 u6 )', ...
    'void unused = rfft_process( csingle* y1, const single* u1, const csingle* u2, const csingle* u3, csingle* u4, const int32 u5, const int32 u6 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'rfft_hexagon.h', ...
          'ImplementationSourceFile', 'rfft_hexagon.c', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'ImplementationSourcePath', fullfile(thisPath, 'src'), ...
          'GenCallback', 'RTW.copyFileToBuildDir', ...
          'AdditionalHeaderFiles', { ...
                'qhmath.h', ...
                'qhcomplex.h', ...
                'qhdsp.h', ...
                'qhdsp_common.h', ...
                'blkutil.h', ...
                'qhdsp_fft_internal.h'}, ...
          'AdditionalIncludePaths', { ...
                fullfile(thisPath, 'inc')}, ...
          'AdditionalSourceFiles', { ...
                'blkutil.c', ...
                'qhdsp_fft_internal.c'}, ...
          'AdditionalSourcePaths', { ...
                fullfile(thisPath, 'src')}, ...
          'SideEffects', true);


hLib.addEntry( hEnt );


%---------- entry: rifft_process ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1[1 1; 1024 1024] = rifft_process( csingle u1[1 1; 1024 1024], csingle* u2[1 1; 1024 1024], csingle* u3[1 1; 1024 1024], csingle* u4[1 1; 1024 1024], single* u5[1 1; 1024 1024], single u6[1 1; 1024 1024], int32 u7, int32 u8, int32 u9 )', ...
    'void unused = rifft_process( single* y1, const csingle* u1, const csingle* u2, const csingle* u3, csingle* u4, const single* u5, single* u6, const int32 u7, const int32 u8, const int32 u9)');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'rfft_hexagon.h', ...
          'ImplementationSourceFile', 'rfft_hexagon.c', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'ImplementationSourcePath', fullfile(thisPath, 'src'), ...
          'GenCallback', 'RTW.copyFileToBuildDir', ...
          'AdditionalHeaderFiles', { ...
                'qhmath.h', ...
                'qhcomplex.h', ...
                'qhdsp.h', ...
                'qhdsp_common.h', ...
                'blkutil.h', ...
                'qhdsp_fft_internal.h'}, ...
          'AdditionalIncludePaths', { ...
                fullfile(thisPath, 'inc')}, ...
          'AdditionalSourceFiles', { ...
                'qhdsp_fft_internal.c',...
                'blkutil.c'}, ...
          'AdditionalSourcePaths', { ...
                fullfile(thisPath, 'src')}, ...
          'SideEffects', true);


hLib.addEntry( hEnt ); 

%---------- entry: fir_process -----------
hEnt = createCRLEntry(hLib, ...
    'single y1[1 1; 8192 8192] = fir_hexagon_process( single u1[1 1; 8192 8192], uint32 u2[1 1; 65536 65536], uint32 u3 )', ...
    'void unused = fir_process( single* y1, const single* u1, uint32* u2, uint32 u3 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'fir_hexagon.h', ...
          'ImplementationSourceFile', 'fir_hexagon.c', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'ImplementationSourcePath', fullfile(thisPath, 'src'), ...
		  'AdditionalIncludePaths',{  ...
                                      fullfile(thisPath, 'inc')}, ...
		  'AdditionalSourceFiles', {  ...
                                      'flt_bkfir.S'}, ...
          'GenCallback', 'RTW.copyFileToBuildDir', ...
          'SideEffects', true);

hLib.addEntry( hEnt ); 
%---------- entry: fir_init ----------- 
hEnt = createCRLEntry(hLib, ...
    'uint32 y1 = fir_hexagon_init( single u1[1 1; 65536 65536], single u2[1 1; 65536 65536], single u3[1 1; 524288 524288], uint32 u4[1 1; 65536 65536], uint32 u5[1 1; 65536 65536], uint32 u6[1 1; 65536 65536], uint32 u7, uint32 u8, uint32 u9, uint32 u10, uint32 u11[1 1; 65536 65536] )', ...
    'void unused = fir_init( uint32* y1, const single* u1, single* u2, single* u3, const uint32* u4, const uint32* u5, const uint32* u6, uint32 u7, uint32 u8, uint32 u9, uint32 u10, uint32* u11 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'fir_hexagon.h', ...
          'ImplementationSourceFile', 'fir_hexagon.c', ...
          'ImplementationHeaderPath',  fullfile(thisPath, 'inc'), ...
          'ImplementationSourcePath',  fullfile(thisPath, 'src'), ...
          'GenCallback', 'RTW.copyFileToBuildDir', ...
          'SideEffects', true);
hLib.addEntry( hEnt ); 

%---------- entry: fireven_process_mt ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1[1 1; 8192 8192] = fireven_hexagon_process_mt( single u1[1 1; 8192 8192], uint32 u2[1 1; 65536 65536], single u3[1 1; 65536 65536], uint32 u4[1 1; 65536 65536] )', ...
    'void unused = fireven_process_mt( single* y1, single* u1, uint32* u2, single* u3, uint32* u4 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'fireven_hexagon.h', ...
          'ImplementationSourceFile', 'fireven_hexagon.c', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'ImplementationSourcePath', fullfile(thisPath, 'src'), ...
          'AdditionalHeaderFiles', { ...
                                     'qhmath.h', ...
                                     'qhcomplex.h', ...
                                     'qhdsp.h', ...
                                     'qhdsp_fft_internal.h', ...
                                     'qhdsp_common.h', ...
                                     'qhl_common.h'}, ...
          'AdditionalIncludePaths',{ ...
                                      fullfile(thisPath, 'inc')}, ...
          'AdditionalSourceFiles', { 'flt_bkfir.S', ...
                                     'qhdsp_fir_af_bose.S'}, ...	
          'GenCallback', 'RTW.copyFileToBuildDir', ...
          'SideEffects', true);
hLib.addEntry( hEnt ); 

%---------- entry: fireven_process_lt ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1[1 1; 8192 8192] = fireven_hexagon_process_lt( single u1[1 1; 8192 8192], uint32 u2[1 1; 65536 65536], single u3[1 1; 65536 65536], uint32 u4[1 1; 65536 65536] )', ...
    'void unused = fireven_process_lt( single* y1, single* u1, uint32* u2, single* u3, uint32* u4 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'fireven_hexagon.h', ...
          'ImplementationSourceFile', 'fireven_hexagon.c', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'ImplementationSourcePath', fullfile(thisPath, 'src'), ...
          'AdditionalHeaderFiles', { ...
                                     'qhmath.h', ...
                                     'qhcomplex.h', ...
                                     'qhdsp.h', ...
                                     'qhdsp_fft_internal.h', ...
                                     'qhdsp_common.h', ...
                                     'qhl_common.h'}, ...
          'AdditionalIncludePaths',{ ...
                                      fullfile(thisPath, 'inc')}, ...
          'AdditionalSourceFiles', { 'flt_bkfir.S', ...
                                     'qhdsp_fir_af_bose.S'}, ...	
          'GenCallback', 'RTW.copyFileToBuildDir', ...
          'SideEffects', true);
hLib.addEntry( hEnt ); 

%---------- entry: fireven_init ----------- 
hEnt = createCRLEntry(hLib, ...
    'uint32 y1 = fireven_hexagon_init( uint32 u1, uint32 u2, uint32 u3, uint32 u4, single u5[1 1; 8192 8192], uint32 u6[1 1; 65536 65536], uint32 u7 )', ...
    'void unused = fireven_init(uint32* y1, uint32 u1, uint32 u2, uint32 u3, uint32 u4, single* u5, uint32* u6, uint32 u7)');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'fireven_hexagon.h', ...
          'ImplementationSourceFile', 'fireven_hexagon.c', ...
          'ImplementationHeaderPath',  fullfile(thisPath, 'inc'), ...
          'ImplementationSourcePath',  fullfile(thisPath, 'src'), ...
          'AdditionalHeaderFiles', { ...
                                     'qhmath.h', ...
                                     'qhcomplex.h', ...
                                     'qhdsp.h', ...
                                     'qhdsp_fft_internal.h', ...
                                     'qhdsp_common.h', ...
                                     'qhl_common.h'}, ...
          'AdditionalIncludePaths',{ ...
                                      fullfile(thisPath, 'inc')}, ...
          'GenCallback', 'RTW.copyFileToBuildDir', ...
          'SideEffects', true);

hLib.addEntry( hEnt ); 
%---------- entry: pooliir_process ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1[1 1; 2097152 2097152] = pooliir_hexagon_process( single u1[1 1; 2097152 2097152], single u2[1 1; 2097152 2097152] )', ...
    'void unused = pooliir_process( single* y1, const single* u1, single* u2 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'pooliir_hexagon.h', ...
          'ImplementationSourceFile', 'pooliir_hexagon.c', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'ImplementationSourcePath', fullfile(thisPath, 'src'), ...
		  'AdditionalHeaderFiles', { ...
                                     'qhmath.h', ...
                                     'qhcomplex.h', ...
                                     'qhdsp.h', ...
                                     'qhdsp_common.h', ...
									 'qhblas.h', ...
                                     'qhdsp_iir.h'}, ...
		  'AdditionalIncludePaths',{ ...
                                      fullfile(thisPath, 'inc')}, ...
		  'AdditionalSourceFiles', { ...
                                     'flt_iir_cas_bq.S'}, ...	
          'GenCallback', 'RTW.copyFileToBuildDir', ...
          'SideEffects', true);

hLib.addEntry( hEnt ); 
%---------- entry: pooliir_init (multiple channel u4) ----------- 
hEnt = createCRLEntry(hLib, ...
'single y1 = pooliir_hexagon_init( single u1[1 1; 2097152 2097152], uint32 u2, uint32 u3, uint32 u4[1 1; 2097152 2097152], single u5[1 1; 2097152 2097152], single u6[1 1; 2097152 2097152], uint32 u7 , uint32 u8,  uint32 u9 )', ...
'void unused = pooliir_init( single* y1, const single* u1, uint32 u2, uint32 u3, const uint32* u4, const single* u5, single* u6, uint32 u7 , uint32 u8, uint32 u9)');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'pooliir_hexagon.h', ...
          'ImplementationSourceFile', 'pooliir_hexagon.c', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'ImplementationSourcePath', fullfile(thisPath, 'src'), ...
		  'AdditionalHeaderFiles', { ...
                                     'qhmath.h', ...
                                     'qhcomplex.h', ...
                                     'qhdsp.h', ...
                                     'qhdsp_common.h', ...
									 'qhblas.h', ...
                                     'qhdsp_iir.h'}, ...
		  'AdditionalIncludePaths',{ ...
                                      fullfile(thisPath, 'inc')}, ...
		  'AdditionalSourceFiles', { ...
                                     'flt_iir_cas_bq.S'}, ...	
          'GenCallback', 'RTW.copyFileToBuildDir', ...
          'SideEffects', true);


hLib.addEntry( hEnt ); 

%---------- entry: pooliir_init (single channel u4) ----------- 

hEnt = createCRLEntry(hLib, ...
'single y1 = pooliir_hexagon_init( single u1[1 1; 2097152 2097152], uint32 u2, uint32 u3, uint32 u4, single u5[1 1; 2097152 2097152], single u6[1 1; 2097152 2097152], uint32 u7 , uint32 u8, uint32 u9 )', ...
'void unused = pooliir_init( single* y1, const single* u1, uint32 u2, uint32 u3, const uint32* u4, const single* u5, single* u6, uint32 u7 , uint32 u8, uint32 u9)');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'pooliir_hexagon.h', ...
          'ImplementationSourceFile', 'pooliir_hexagon.c', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'ImplementationSourcePath', fullfile(thisPath, 'src'), ...
		  'AdditionalHeaderFiles', { ...
                                     'qhmath.h', ...
                                     'qhcomplex.h', ...
                                     'qhdsp.h', ...
                                     'qhdsp_common.h', ...
									 'qhblas.h', ...
                                     'qhdsp_iir.h'}, ...
		  'AdditionalIncludePaths',{ ...
                                      fullfile(thisPath, 'inc')}, ...
		  'AdditionalSourceFiles', { ...
                                     'flt_iir_cas_bq.S'}, ...			 
          'GenCallback', 'RTW.copyFileToBuildDir', ...
          'SideEffects', true);


hLib.addEntry( hEnt ); 
%---------- entry: firup_init (generic) ----------- 
hEnt = createCRLEntry(hLib, ...
    'uint32 y1 = firup_generic_init( single u1[1 1; 8192 8192], uint32 u2, uint32 u3, uint32 u4, uint32 u5, uint32 u6[1 1; 1024 1024])', ...
    'void unused = firup_init(uint32* y1, single* u1, uint32 u2, uint32 u3, uint32 u4, uint32 u5, uint32* u6)');

hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'firup.h', ...
          'ImplementationSourceFile', 'firup.c', ...
          'ImplementationHeaderPath',  fullfile(SharedPath, 'inc'), ...
          'ImplementationSourcePath',  fullfile(SharedPath, 'src'), ...
          'GenCallback', 'RTW.copyFileToBuildDir', ...
          'SideEffects', true);

hLib.addEntry( hEnt ); 

%---------- entry: firup_process (generic) ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1[1 1; 8192 8192] = firup_generic_process( single u1[1 1; 8192 8192], single u2[1 1; 65536 65536], uint32 u3[1 1; 1024 1024], uint32 u4)', ...
    'void unused = firup_process( single* y1, single* u1, single* u2, uint32* u3 , uint32 u4)');

hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'firup.h', ...
          'ImplementationSourceFile', 'firup.c', ...
          'ImplementationHeaderPath', fullfile(SharedPath, 'inc'), ...
          'ImplementationSourcePath', fullfile(SharedPath, 'src'), ...
          'GenCallback', 'RTW.copyFileToBuildDir', ...
          'SideEffects', true);
hLib.addEntry( hEnt ); 
%---------- entry: firup_init (hexagon) ----------- 
hEnt = createCRLEntry(hLib, ...
    'uint32 y1 = firup_hexagon_init( single u1[1 1; 8192 8192], uint32 u2, uint32 u3, uint32 u4, uint32 u5, uint32 u6[1 1; 1024 1024])', ...
    'void unused = firup_init(uint32* y1, single* u1, uint32 u2, uint32 u3, uint32 u4, uint32 u5, uint32* u6)');

hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'firup.h', ...
          'ImplementationSourceFile', 'firup.c', ...
          'ImplementationHeaderPath',  fullfile(thisPath, 'inc'), ...
          'ImplementationSourcePath',  fullfile(SharedPath, 'src'), ...
          'AdditionalHeaderFiles', { ...
                                     'qhmath.h', ...
                                     'qhcomplex.h', ...
                                     'qhdsp.h', ...
                                     'qhdsp_fft_internal.h', ...
                                     'qhdsp_common.h', ...
                                     'qhl_common.h'}, ...
          'AdditionalIncludePaths',{ ...
                                      fullfile(thisPath, 'inc')}, ...
          'GenCallback', 'RTW.copyFileToBuildDir', ...
          'SideEffects', true);

hLib.addEntry( hEnt ); 

%---------- entry: firup_process (hexagon) ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1[1 1; 8192 8192] = firup_hexagon_process( single u1[1 1; 8192 8192], single u2[1 1; 65536 65536], uint32 u3[1 1; 1024 1024], uint32 u4)', ...
    'void unused = firup_process( single* y1, single* u1, single* u2, uint32* u3 , uint32 u4)');

hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'firup.h', ...
          'ImplementationSourceFile', 'firup.c', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'ImplementationSourcePath', fullfile(SharedPath, 'src'), ...
          'AdditionalHeaderFiles', { ...
                                     'qhmath.h', ...
                                     'qhcomplex.h', ...
                                     'qhdsp.h', ...
                                     'qhdsp_fft_internal.h', ...
                                     'qhdsp_common.h', ...
                                     'qhl_common.h'}, ...
          'AdditionalIncludePaths',{ ...
                                      fullfile(thisPath, 'inc')}, ...
          'AdditionalSourcePaths',{ ...
                                      fullfile(thisPath, 'src')}, ...
          'AdditionalSourceFiles', { ...
                                     'qhdsp_fir_af_bose.S'}, ...	
          'GenCallback', 'RTW.copyFileToBuildDir', ...
          'SideEffects', true);
hLib.addEntry( hEnt ); 

%---------- entry: circindex ----------- 
hEnt = createCRLEntry(hLib, ...
    'int32 y1 = circindex( int32 u1, int32 u2, int32 u3 )', ...
    'int32 y1 = circindex( int32 u1, int32 u2, int32 u3 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'circbuf.h',...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'GenCallback', 'RTW.copyFileToBuildDir',...
          'SideEffects', true);
hLib.addEntry( hEnt ); 

%---------- entry: copysignf ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1 = copysignf( single u1, single u2 )', ...
    'single y1 = copysignf( single u1, single u2 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'math.h', ...
          'SideEffects', true);
hLib.addEntry( hEnt ); 


%---------- entry: log2 ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1 = log2( single u1 )', ...
    'single y1 = qhmath_log2_f( single u1 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'qhmath.h', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'GenCallback', 'RTW.copyFileToBuildDir');



hLib.addEntry( hEnt ); 

%---------- entry: cot ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1 = cot( single u1 )', ...
    'single y1 = qhmath_cot_f( single u1 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'qhmath.h', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'GenCallback', 'RTW.copyFileToBuildDir');



hLib.addEntry( hEnt ); 

%---------- entry: rnc_control_filter ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1[1 2; 1 6] = rnc_control_filt( single u1[275 3; 400 12], single u2[125 3 2; 200 12 6], int32 u3, int32 u4, int32 u5, int32 u6 )', ...
    'void unused = control_filter( single* y1, single* u1, single* u2, int32 u3, int32 u4, int32 u5, int32 u6 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'rnc_custom_replacements.h', ...
          'ImplementationSourceFile', 'rnc_custom_replacements.c', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'ImplementationSourcePath', fullfile(thisPath, 'src'), ...
          'GenCallback', 'RTW.copyFileToBuildDir', ...
          'SideEffects', true);



hLib.addEntry( hEnt ); 

%---------- entry: rnc_filter_update ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1 = rnc_filter_update( single u1[125 2; 220 9], single u2[125 2; 220 9], single u3[125 20; 220 35], single u4[125 20; 220 35], int32 u5, int32 u6, int32 u7, int32 u8 )', ...
    'single y1 = filter_update( single* u1, single* u2, single* u3, single* u4, int32 u5, int32 u6, int32 u7, int32 u8 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'rnc_custom_replacements.h', ...
          'ImplementationSourceFile', 'rnc_custom_replacements.c', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'ImplementationSourcePath', fullfile(thisPath, 'src'), ...
          'GenCallback', 'RTW.copyFileToBuildDir', ...
          'SideEffects', true);



hLib.addEntry( hEnt ); 

%---------- entry: abs ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1 = abs( single u1 )', ...
    'single y1 = qhmath_abs_f( single u1 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'qhmath.h', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'GenCallback', 'RTW.copyFileToBuildDir');



hLib.addEntry( hEnt ); 

%---------- entry: acos ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1 = acos( single u1 )', ...
    'single y1 = qhmath_acos_f( single u1 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'qhmath.h', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'GenCallback', 'RTW.copyFileToBuildDir');



hLib.addEntry( hEnt ); 

%---------- entry: asin ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1 = asin( single u1 )', ...
    'single y1 = qhmath_asin_f( single u1 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'qhmath.h', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'GenCallback', 'RTW.copyFileToBuildDir');



hLib.addEntry( hEnt ); 

%---------- entry: atan ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1 = atan( single u1 )', ...
    'single y1 = qhmath_atan_f( single u1 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'qhmath.h', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'GenCallback', 'RTW.copyFileToBuildDir');



hLib.addEntry( hEnt ); 

%---------- entry: atan2 ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1 = atan2( single u1, single u2 )', ...
    'single y1 = qhmath_atan2_f( single u1, single u2 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'qhmath.h', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'GenCallback', 'RTW.copyFileToBuildDir');

hEnt.EntryInfo.Algorithm = 'RTW_UNSPECIFIED';


hLib.addEntry( hEnt ); 

%---------- entry: ceil ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1 = ceil( single u1 )', ...
    'single y1 = qhmath_ceil_f( single u1 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'qhmath.h', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'GenCallback', 'RTW.copyFileToBuildDir');



hLib.addEntry( hEnt ); 

%---------- entry: cos ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1 = cos( single u1 )', ...
    'single y1 = qhmath_cos_f( single u1 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'qhmath.h', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'GenCallback', 'RTW.copyFileToBuildDir');

hEnt.EntryInfo.Algorithm = 'RTW_UNSPECIFIED';


hLib.addEntry( hEnt ); 

%---------- entry: cosh ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1 = cosh( single u1 )', ...
    'single y1 = qhmath_cosh_f( single u1 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'qhmath.h', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'GenCallback', 'RTW.copyFileToBuildDir');



hLib.addEntry( hEnt ); 

%---------- entry: exp ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1 = exp( single u1 )', ...
    'single y1 = qhmath_exp_f( single u1 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'qhmath.h', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'GenCallback', 'RTW.copyFileToBuildDir');



hLib.addEntry( hEnt ); 

%---------- entry: floor ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1 = floor( single u1 )', ...
    'single y1 = qhmath_floor_f( single u1 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'qhmath.h', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'GenCallback', 'RTW.copyFileToBuildDir');



hLib.addEntry( hEnt ); 

%---------- entry: hypot ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1 = hypot( single u1, single u2 )', ...
    'single y1 = qhmath_hypot_f( single u1, single u2 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'qhmath.h', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'GenCallback', 'RTW.copyFileToBuildDir');



hLib.addEntry( hEnt ); 

%---------- entry: log ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1 = log( single u1 )', ...
    'single y1 = qhmath_log_f( single u1 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'qhmath.h', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'GenCallback', 'RTW.copyFileToBuildDir');



hLib.addEntry( hEnt ); 

%---------- entry: log10 ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1 = log10( single u1 )', ...
    'single y1 = qhmath_log10_f( single u1 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'qhmath.h', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'GenCallback', 'RTW.copyFileToBuildDir');



hLib.addEntry( hEnt ); 

%---------- entry: pow ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1 = pow( single u1, single u2 )', ...
    'single y1 = qhmath_pow_f( single u1, single u2 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'qhmath.h', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'GenCallback', 'RTW.copyFileToBuildDir');



hLib.addEntry( hEnt ); 

%---------- entry: rSqrt ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1 = rSqrt( single u1 )', ...
    'single y1 = qhmath_rsqrt_f( single u1 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'qhmath.h', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'GenCallback', 'RTW.copyFileToBuildDir');

hEnt.EntryInfo.Algorithm = 'RTW_UNSPECIFIED';


hLib.addEntry( hEnt ); 

%---------- entry: sin ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1 = sin( single u1 )', ...
    'single y1 = qhmath_sin_f( single u1 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'qhmath.h', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'GenCallback', 'RTW.copyFileToBuildDir');

hEnt.EntryInfo.Algorithm = 'RTW_UNSPECIFIED';


hLib.addEntry( hEnt ); 

%---------- entry: sinh ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1 = sinh( single u1 )', ...
    'single y1 = qhmath_sinh_f( single u1 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'qhmath.h', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'GenCallback', 'RTW.copyFileToBuildDir');



hLib.addEntry( hEnt ); 

%---------- entry: sqrt ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1 = sqrt( single u1 )', ...
    'single y1 = qhmath_sqrt_f( single u1 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'qhmath.h', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'GenCallback', 'RTW.copyFileToBuildDir');



hLib.addEntry( hEnt ); 

%---------- entry: tan ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1 = tan( single u1 )', ...
    'single y1 = qhmath_tan_f( single u1 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'qhmath.h', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'GenCallback', 'RTW.copyFileToBuildDir');



hLib.addEntry( hEnt ); 

%---------- entry: tanh ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1 = tanh( single u1 )', ...
    'single y1 = qhmath_tanh_f( single u1 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'qhmath.h', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'GenCallback', 'RTW.copyFileToBuildDir');



hLib.addEntry( hEnt ); 

%---------- entry: RTW_OP_DIV ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1 = single u1 / single u2', ...
    'single y1 = qhmath_div_f( single u1, single u2 )');
hEnt.setTflCOperationEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'qhmath.h', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'GenCallback', 'RTW.copyFileToBuildDir');


hLib.addEntry( hEnt ); 


