function hLib = ArmCodeReplacementLibraryTable

thisFile = mfilename('fullpath');
[thisPath, ~] = fileparts(thisFile);
hLib = RTW.TflTable;

%---------- entry: fir_armv7v8_process ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1[1 1; 1024 1024] = fir_armv7v8_process( single u1[1 1; 1024 1024], uint32 u2[1 1; 65536 65536], uint32 u3 )', ...
    'void unused = fir_process( single* y1, const single* u1, uint32* u2, uint32 u3 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'fir_armv7v8.h', ...
          'ImplementationSourceFile', 'fir_armv7v8.c', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'ImplementationSourcePath', fullfile(thisPath, 'src'), ...
	      'AdditionalIncludePaths',{ ...
                                      fullfile(thisPath, 'inc')}, ...
          'GenCallback', 'RTW.copyFileToBuildDir', ...
          'SideEffects', true);

hLib.addEntry( hEnt ); 


%---------- entry: fir_armv7v8_init ----------- 
hEnt = createCRLEntry(hLib, ...
    'uint32 y1 = fir_armv7v8_init( single u1[1 1; 1024 1024], single u2[1 1; 65536 65536], single u3[1 1; 65536 65536], uint32 u4[1 1; 1024 1024], uint32 u5[1 1; 1024 1024], uint32 u6[1 1; 1024 1024], uint32 u7, uint32 u8, uint32 u9, uint32 u10, uint32 u11[1 1; 65536 65536] )', ...
    'void unused = fir_init( uint32* y1, const single* u1, single* u2, single* u3, const uint32* u4, const uint32* u5, const uint32* u6, uint32 u7, uint32 u8, uint32 u9, uint32 u10, uint32* u11 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'fir_armv7v8.h', ...
          'ImplementationSourceFile', 'fir_armv7v8.c', ...
          'ImplementationHeaderPath',  fullfile(thisPath, 'inc'), ...
          'ImplementationSourcePath',  fullfile(thisPath, 'src'), ...
          'GenCallback', 'RTW.copyFileToBuildDir', ...
          'SideEffects', true);

hLib.addEntry( hEnt ); 


%---------- entry: fireven_armv7v8_process ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1[1 1; 1024 1024] = fireven_armv7v8_process( single u1[1 1; 1024 1024], uint32 u2[1 1; 65536 65536], single u3[1 1; 65536 65536], uint32 u4[1 1; 65536 65536] )', ...
    'void unused = fireven_process_armv7v8( single* y1, single* u1, uint32* u2, single* u3, uint32* u4 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'fireven_process_armv7v8.h', ...
          'ImplementationSourceFile', 'fireven_process_armv7v8.c', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'ImplementationSourcePath', fullfile(thisPath, 'src'), ...
          'AdditionalIncludePaths',{ ...
                                      fullfile(thisPath, 'inc')}, ...
          'GenCallback', 'RTW.copyFileToBuildDir', ...
          'SideEffects', true);



hLib.addEntry( hEnt ); 



%---------- entry: fireven_armv7v8_process_init ----------- 
hEnt = createCRLEntry(hLib, ...
    'uint32 y1 = fireven_armv7v8_process_init( uint32 u1, uint32 u2, uint32 u3, uint32 u4, single u5[1 1; 1024 1024], uint32 u6[1 1; 65536 65536] )', ...
    'void unused = fireven_process_armv7v8_init(uint32* y1, uint32 u1, uint32 u2, uint32 u3, uint32 u4, single* u5, uint32* u6 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'fireven_process_armv7v8.h', ...
          'ImplementationSourceFile', 'fireven_process_armv7v8.c', ...
          'ImplementationHeaderPath',  fullfile(thisPath, 'inc'), ...
          'ImplementationSourcePath',  fullfile(thisPath, 'src'), ...
          'AdditionalIncludePaths',{ ...
                                      fullfile(thisPath, 'inc')}, ...
          'GenCallback', 'RTW.copyFileToBuildDir', ...
          'SideEffects', true);

hLib.addEntry( hEnt ); 


%---------- entry: pooliir_armv7v8_process ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1[1 1; 2097152 2097152]  = pooliir_armv7v8_process( single u1[1 1; 2097152 2097152] , single u2[1 1; 2097152 2097152]  )', ...
    'void unused = pooliir_process( single* y1, const single* u1, single* u2 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'pooliir_armv7v8.h', ...
          'ImplementationSourceFile', 'pooliir_armv7v8.c', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'ImplementationSourcePath', fullfile(thisPath, 'src'), ...
	    'AdditionalIncludePaths',{ ...
                                      fullfile(thisPath, 'inc')}, ...
          'GenCallback', 'RTW.copyFileToBuildDir', ...
          'SideEffects', true);



hLib.addEntry( hEnt ); 


%---------- entry: pooliir_armv7v8_init (multiple channel u4) ----------- 
hEnt = createCRLEntry(hLib, ...
'single y1 = pooliir_armv7v8_init( single u1[1 1; 2097152 2097152] , uint32 u2, uint32 u3, uint32 u4[1 1; 2097152 2097152] , single u5[1 1; 2097152 2097152] , single u6[1 1; 2097152 2097152] , uint32 u7 )', ...
'void unused = pooliir_init( single* y1, const single* u1, uint32 u2, uint32 u3, const uint32* u4, const single* u5, single* u6, uint32 u7 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'pooliir_armv7v8.h', ...
          'ImplementationSourceFile', 'pooliir_armv7v8.c', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'ImplementationSourcePath', fullfile(thisPath, 'src'), ...
	    'AdditionalIncludePaths',{ ...
                                      fullfile(thisPath, 'inc')}, ...
          'GenCallback', 'RTW.copyFileToBuildDir', ...
          'SideEffects', true);


hLib.addEntry( hEnt ); 


%---------- entry: pooliir_armv7v8_init (single channel u4) ----------- 
hEnt = createCRLEntry(hLib, ...
'single y1 = pooliir_armv7v8_init( single u1[1 1; 2097152 2097152] uint32 u2, uint32 u3, uint32 u4, single u5[1 1; 2097152 2097152] , single u6[1 1; 2097152 2097152] , uint32 u7 )', ...
'void unused = pooliir_init( single* y1, const single* u1, uint32 u2, uint32 u3, const uint32* u4, const single* u5, single* u6, uint32 u7 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'pooliir_armv7v8.h', ...
          'ImplementationSourceFile', 'pooliir_armv7v8.c', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'ImplementationSourcePath', fullfile(thisPath, 'src'), ...
	    'AdditionalIncludePaths',{ ...
                                      fullfile(thisPath, 'inc')}, ...		 
          'GenCallback', 'RTW.copyFileToBuildDir', ...
          'SideEffects', true);


hLib.addEntry( hEnt ); 

%---------- entry: rfft_process ----------- 
hEnt = createCRLEntry(hLib, ...
    'csingle y1[1 1; 1024 1024] = rfft_armv7v8_process( single u1[1 1; 8192 8192], uint32 u2, uint32 u3[1 1; 8192 8192], uint32 u4 )', ...
    'void unused = rfft_process( csingle* y1, const single* u1, uint32 u2, uint32* u3, uint32 u4)');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'rfft_armv7v8.h', ...
          'ImplementationSourceFile', 'rfft_armv7v8.c', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'ImplementationSourcePath', fullfile(thisPath, 'src'), ...
          'GenCallback', 'RTW.copyFileToBuildDir', ...
          'AdditionalHeaderFiles', { ...
                'NE10_dsp.h', ...
                'NE10_fft_bfly.h', ...
                'NE10_fft_common_varibles.h', ...
                'NE10_fft_cplx_ops.h', ...
                'NE10_fft_debug_macro.h', ...
                'NE10_fft_generic_float32.h', ...
                'NE10_fft.h', ...
                'NE10_fft.neonintrinsic.h', ...
                'NE10_macros.h', ...
                'NE10_types.h'}, ...
          'AdditionalIncludePaths', { ...
                fullfile(thisPath, 'inc'), ...
                fullfile(thisPath, 'NE10Lib')}, ...
          'AdditionalSourceFiles', { ...
                'NE10_fft_float32.neon.c', ...
                'NE10_fft_float32.neonintrinsic.c', ...
                'NE10_fft_generic_float32.neonintrinsic.cpp', ...
                'NE10_fft.c'}, ...
          'AdditionalSourcePaths', { ...
                fullfile(thisPath, 'src'), ...
                fullfile(thisPath, 'NE10Lib')}, ...
          'SideEffects', true);


hLib.addEntry( hEnt ); 


%---------- entry: rifft_process ----------- 
hEnt = createCRLEntry(hLib, ...
    'single y1[1 1; 1024 1024] = rifft_armv7v8_process( csingle u1[1 1; 8192 8192], uint32 u2, uint32 u3, uint32 u4, single u5[1 1; 8192 8192], single u6[1 1; 8192 8192], uint32 u7[1 1; 8192 8192] )', ...
    'void unused = rifft_process( single* y1, csingle* u1, uint32 u2, uint32 u3, uint32 u4, const single* u5, single* u6, uint32* u7 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'rfft_armv7v8.h', ...
          'ImplementationSourceFile', 'rfft_armv7v8.c', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'ImplementationSourcePath', fullfile(thisPath, 'src'), ...
          'GenCallback', 'RTW.copyFileToBuildDir', ...
          'AdditionalHeaderFiles', { ...
                'NE10_dsp.h', ...
                'NE10_fft_bfly.h', ...
                'NE10_fft_common_varibles.h', ...
                'NE10_fft_cplx_ops.h', ...
                'NE10_fft_debug_macro.h', ...
                'NE10_fft_generic_float32.h', ...
                'NE10_fft.h', ...
                'NE10_fft.neonintrinsic.h', ...
                'NE10_macros.h', ...
                'NE10_types.h'}, ...
          'AdditionalIncludePaths', { ...
                fullfile(thisPath, 'inc'), ...
                fullfile(thisPath, 'NE10Lib')}, ...
          'AdditionalSourceFiles', { ...
                'NE10_fft_float32.neon.c', ...
                'NE10_fft_float32.neonintrinsic.c', ...
                'NE10_fft_generic_float32.neonintrinsic.cpp', ...
                'NE10_fft.c'}, ...
          'AdditionalSourcePaths', { ...
                fullfile(thisPath, 'src'), ...
                fullfile(thisPath, 'NE10Lib')}, ...
          'SideEffects', true);


hLib.addEntry( hEnt ); 


%---------- entry: rfft_init ----------- 
hEnt = createCRLEntry(hLib, ...
    'uint32 y1 = rfft_armv7v8_init( uint32 u1, uint32 u2[1 1; 8192 8192] )', ...
    'void unused = rfft_init( uint32* y1, uint32 u1, uint32* u2 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'rfft_armv7v8.h', ...
          'ImplementationSourceFile', 'rfft_armv7v8.c', ...
          'ImplementationHeaderPath', fullfile(thisPath, 'inc'), ...
          'ImplementationSourcePath', fullfile(thisPath, 'src'), ...
          'GenCallback', 'RTW.copyFileToBuildDir', ...
          'AdditionalIncludePaths', { ...
                fullfile(thisPath, 'inc')}, ...
          'AdditionalSourcePaths', { ...
                fullfile(thisPath, 'src')}, ...
          'AdditionalSourcePaths', { ...
                fullfile(thisPath, 'NE10Lib')}, ...
          'SideEffects', true);

hLib.addEntry( hEnt ); 






