/*
 **
 ** Source file generated on August 27, 2018 at 12:04:48.
 **
 ** Copyright (C) 2018 Analog Devices Inc., All Rights Reserved.
 **
 ** This file is generated automatically based upon the options selected in
 ** the DMC Initialization configuration dialog. Changes to this configuration should be made by
 ** changing the appropriate options rather than editing this file.
 **
 */

/*!
 * @file     adi_dmc_2156x_config.h
 *
 * @brief    DMC controller configuration header file generated by plugin
 *
 * @version  $Revision: 47521 $
 *
 * @date     $Date: 2018-10-15 10:42:57 -0400 (Mon, 15 Oct 2018) $
 *
 * @details
 *           This is the header file for the DMC controller initialization
 */

#ifndef _ADI_DMC_CFG0_H_
#define _ADI_DMC_CFG0_H_

#include "adi_dmc.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Initializes DMC controller */
uint32_t adi_dmc_cfg0_init(void);

#ifdef __cplusplus
}
#endif

#endif /* _ADI_DMC_CFG0_H_ */
/*@}*/
